language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
- windows
matrix:
  exclude:
  - os: windows
    node_js: stable
after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: ZrRh5+vDhXU2ysv7ZRjTXszQ5vgMniBfXQmtL/kNGnoC6lbucHe8bxIGZPPlxIS8uAeNZEvrA0vTsP2RU3Q5H+G8AB2NJSswT5JVfMJpfUJ3C5IcYSKGu4LMAfQRzR1wxP6huZotSq6e/kHSMpzgTFTxfTtlvLlUg5nxbm26VC6iB4Y3xEk3KWtoor/xs6bbgGQaE8fAdJYwABBdwfQ/9qBlzgZs399IAby54AkDpQlwwOg6KWIRJwcEvn7JPdH5jaI78ddqAWLrq0bcgws3SLbJjlEejpkufOgQl/MgeRDStEmJna2AYzS8zO23ohCepQC7TWw71RZCfkm0Bs/VnlnJWDY1vhM29iv23z2Ui/FWOyXyJbJAoaqT/3dehWinunZNZjBPiiLj+zwDvkFia9KkRfC9EbAQNRs6lQwG7jigeM33POIGn685QJFTQAIrf56NszfRrjD0xkqcjBuwgYRiuoOiN9q1hSKBy8juNr9HXxhxK6AvRYvvH/ryM9CfWd02Y7jGFmvpvi12AfdEL1k1CxmrtdN5r0jK01NGNZK5mQ9FWE61t/g36L8ZzB5MpvlHtMfYGpr6074BN1WIDDxaANb14iTDP+pEoRmXytZZ6kBU9+H2Tz6NcERYAjJjeYQq9n5/yvGqV3JWiOzW1BRLt+kBHhcKzHFDWognoRk=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: a6xn01+NYPxraiZRKKhkKj7h0i/y/ipqZuHWEawblxllLhm0TevOINBenjkqRcHW+o6wtGa/7b5aNcG9GOb3y1V6oue4xmf2ujWErWkQn0/5yc/KG0NZaHYKKZIAnxKY4FDr+/rCs5JdXRutfZxCYzedBZ5iBglB8mA33UWZ1ZIV+xI3OJMpAJGUungAzomXohFQkfWMQ5mtkyCFZLV/Ev3o1pLcE+adMrSZg25D8lI/exMEa6d6NGfc6s1SKXZM2Gma5hKGgK+SYrTMdFeq19jKmvHk0B1yQdqsmS3KbOJQtj2hD/D38IMTVVIUQlazHqG++oUI92Z0YOnnFe9eM7nVfdjCzBKqSo67XOpFtrMPjUMJrlIPH2DQgx0+gSQpVyHx8lM9ocwcSh/AH58iKevCavPrUcjkmxloisP9vqdSUuhVgQaSBT1nah72yMh/wtlc8vc1wNVOExrcXetyfHPM1g4rwSjTSp6/xc2jZlG7BV4x9oL1vbRgp5lunEhlVJzC3weYt12ayemVRhOTTdb1HiYq5W7R/rLJD/A+tsJhd3QDSNZy8/chIZsjZv5w6NuwX5rYRieMQjNbNin5eUQNwWIln7Ra5T9pDnF/c7mbhF9Bd/Cj8wf3/L+2ENJBKkp0vvXlai5YGiRXmrFQXyExWT94u5ZMa2K3gV54avk=
