language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
- windows
matrix:
  exclude:
  - os: windows
    node_js: stable
after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: MwbHE9APGIbWX7W8/ZhoxUgUJ/Rtd7z4KOR92YdUJYh1dRRSm/9fgBckNaMPGEQRXqgQXVfKIkAJJ96wBcyoXHuoAfFGJALz0W9G9shEww85Fw4cx71ZsuPb0hlGizZ9QPNkQe/myXBZm7F4xYbP7W4ygb/6JlS68HWU8n7D5CG9Enl9G6GmIDgdWgt/k3VI6LtD7nclLuFG5qsTDiOGNxf+5GbsWAhgsVEO7GzQICwF2QbQL9BQbr9iSGGb5Z3xUyNntchRUe/x7qPM9JCTmbAezgKQsfv5GG0U7G6gLnSuswIFrdpIbrj5FMXkOyarMyJMi3toWztZQ8NeS2v3MxceeNVtV2ZBAUe7WFWptsICQeOUna6L7otiaa6fg7cMsSyKhN1FvrhHecx9g+vbZhr1RBrLXFeNBV5yx4HSCiFi67k7ByAALC7w+vth/O4cPqM1hTxwyMxToh7tSrjGgUk0I4NBmLBsg+WmhmTphX5mBmFUKQg62o/s2HYz8mozcLbor9DiiqiDsfYaTWGl4KnCCp+5FSs8Pc4WRT7FPXxnwzYeukZomWw1k6NBssKUB5mt4y3MKDDEIrSvVBq3+IBy6MYKhGRgWsHn4TtJrX/+a//YtLvH5xXBlfTCufxBh2jK+WjHAh/CT9JOxONhGQtZfwj/w8KzNn82+2KlNh4=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: GlTFpA33vm8waeJKwuswmDI0jciB3KA++hXTPsjLKTef0DU6koqp1OIpLCqtg4d6z1FmsrHCrSHU/u/NwAZ/PxmyZr1CiOnwicgIhLcds+lWetRkDUTaiIRdTy4Of2LAHVPtWR2/MUxuP38BcnbXZjpydxhDnIPLcuIk5tZ1hVdCupyUSMU9+oKZ8C32bo03V7TvkpdGLIW8CIr0nZ8PXRs+w8QS4Z5ZVoXoOb9+nX5uGejub2+iugLSS7dsiYwRHxoqQuIa8haveh3KPhTGGD/ClpHZs/1xgGpzo1IUErohkRJ2gJK4GvvCpIk43QxLxC6ugKr1OJK0AvnjbpfTBTk1x3T42eWK9JZj7vEAI6pETXVMfOTE1jHbFdMPSdoVsC2Dmkqf48sIZVZom+Ls+UljRpq9AHRma8q0YvQ/VPq19EBWv3kP6XWkFmZYmm/VZC4rUcLQQp13TX+BYetSn/KM/GZchgGWTYy95X3dcFq1jzRhKfvcgKiuNfr8VO1f918QZMhGlx3yMWLe2ri+QhjUXSlklrXMuLr63FqmudoHLiLC4o04ob2glvNVErNC8ZWlm/OU93zpKpc/pYITUSf1nnd461fmhDH/GHA/afiweb/lhMbWX6TzwXYVT+5wuD+X6qDwmEYvvD9iST+iUCF32xXYS0mJbQXstXBXoL8=
