language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
- windows
matrix:
  exclude:
  - os: windows
    node_js: stable
after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: eN2Q51RFMUMcSMK/qsCCcM+qNzM+MUJXDTyzHD/WJg7S8iPzCdH4p2lwEeBu8S3XWj/AioU83NiAs5rcWhKIKMsbAuTX7LIns81kdA+Sa0Dqw8EM97emFoctFFYUIRJP/ufugiLXygTuzi6+cq0J7l3MsN/qS4If18rq80T8q6n6Dyc2raccCHZSUdIkcf0xL/smeYBk61y9ilEUwqpOjQx5REkv1snbes1hVKWm+vCidUhO1YmQ+jkvfbRHWlZwmlbe+uaxYPlMaaFGAmTSvX55GTkd0fY3E8uvU9aNJwdYuTbbf5crPh9S3sWJfeR4UxG962Th3tARigD8ymljqKIenOT17tXJq7UuNmf59q/VNvPNats4WTA+w4Nn7Vq9tuo4CoSTL1RLAl1zXkkn+hpTFxSEtMoNOtQcYSCHVauUrLg5le5Lap2apYSoX9DQqMD5jHzzHjjopBd8YpYkddC4BUcknMVlOrf6Th5uY8nZJOYTcRSG4mg0aLq3qFR5vOwKvEFASflbGvtDn6tjopxj/Z0cnuFCh7zX5qSfFfT4NLK8uN589OjoYGpBEJN4sb8pSRtKwANwPdEdHVVG08Bxqms9N4lqsysgEuoG3k2645l2+o3aKPavrEKaY7ajvctB01en9Hs/Qz9ZGvGBY3FVAnGqlvENTH7vQu2lPb8=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: S3ub3oyzIP8hnVcW/pPDPkXA6YpPPI4oVyQhI0jASVX2TDQD99qsffzT/Fg2+Gk8v/hq67rg7HHZkClDHXRVMRyv+2zTnQx2f0qVpFRVxycMA275pqQcQyxjA7HDhsT9nZWuIQn2hEK4nlXIvPffRxfar0mPy3amk4H+6ybxIrRXbM+3GupACSVVan/4cVvROd1j7gU/igbfMgUc4iw8rXdoH5L7malWks4UhLU4xzo12lDH758CKxZQjDmOuPOYO7rQUiYhOQDaIZlLWipgTtgKNCtUek3+iEesu+yip0qIpis5s+yJN+cZNT3aMqmocuZHxJKnpq8TT9abJkue9H/e08yssAdX+0ePAhrhNbkPs6Eob9TkiQkDXgyc/Iu5Ffx61L3wR9MjxdHhfBhKQ9+JEDeMk6veyToMyLIvnWDEyTsZT5w2FcMRDETRneyLTx1s3oaA39QXYS9hiNGhAbQ/rFZncrM0DLqzN1wkZHl9v+Pdbz6dC+2LqZhuDiejJbfibzSeEk8fDxAgmdu0cnCGLCtdNcVnOPxOVqDk0LgP/92zLjSVhuRCChkGdcy2WW1zmpFuOA98vhYsBnukd8ndFF8AF5mnpNZ9tq65tPzU+GnKSZyWMaVmDDz6IW2l8UF4jurNXWvSAbiax8ASKhn3+t8ChrZ3jR2w5nf7ZYE=
