language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
- windows
matrix:
  exclude:
  - os: windows
    node_js: stable
after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: pw4T3ylGQGb+3bAzEZg4Nrn9iXroyqN/tF27F2NmiiUYez7U4XI/MXZ6XmqEYNYsgmPc9KSv1r+wQmsbKB1a4WB16/GETgFY/ygAksfyz644kmDTuYYg+j/Nz/tjRoOWF8t9QunpGmjyGnGA3k9BwfyrSJBCFoLP6VkvHNICNSEOARsJsyQ4sHIiZTvw6PlJ/a05xnKZNZXhAPGM0QF2pQCNSQr9pstii6IoC8CKvXgpFINnWyl6WzVhcOXDnDeIYm9k7w81no8Q/YbbfW5YjwepcCJJYfQvii60hhR0FomRvGocFhSYY/S9QKJQgTEfeDhQm9ztSaufX6sv7aHFlIQhfF70gge7uXwWEOQnyhVZCjia/5k19Ve/4YJ+2KgdcTTg2f2mUgAUThLuf8C9x62e78I5hsleIYRy21Tf7gIJK9s7Vp0jDlnCbwooJmvnc/DPtDuKm3y0d4EJq3OOLOJSZBlM348c8dCUeiZfdVOTBprykpl4NayBbgPl4NIFHucdRekC05oXIxRFC3LIzSxfVo3NniO7H3g9/sw79kX1gRZuOT37XEJKyYz/8MnywDsNW2Up9mBy6mot70obNGcmIV8eZGr+FnkqtGsW79YuLi6PdNUj9wHjIZWfXR6SIqy2fxqpr0JE+jDi7taBISd9n2p5TeS4cKhlIN9sBzs=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: GlTFpA33vm8waeJKwuswmDI0jciB3KA++hXTPsjLKTef0DU6koqp1OIpLCqtg4d6z1FmsrHCrSHU/u/NwAZ/PxmyZr1CiOnwicgIhLcds+lWetRkDUTaiIRdTy4Of2LAHVPtWR2/MUxuP38BcnbXZjpydxhDnIPLcuIk5tZ1hVdCupyUSMU9+oKZ8C32bo03V7TvkpdGLIW8CIr0nZ8PXRs+w8QS4Z5ZVoXoOb9+nX5uGejub2+iugLSS7dsiYwRHxoqQuIa8haveh3KPhTGGD/ClpHZs/1xgGpzo1IUErohkRJ2gJK4GvvCpIk43QxLxC6ugKr1OJK0AvnjbpfTBTk1x3T42eWK9JZj7vEAI6pETXVMfOTE1jHbFdMPSdoVsC2Dmkqf48sIZVZom+Ls+UljRpq9AHRma8q0YvQ/VPq19EBWv3kP6XWkFmZYmm/VZC4rUcLQQp13TX+BYetSn/KM/GZchgGWTYy95X3dcFq1jzRhKfvcgKiuNfr8VO1f918QZMhGlx3yMWLe2ri+QhjUXSlklrXMuLr63FqmudoHLiLC4o04ob2glvNVErNC8ZWlm/OU93zpKpc/pYITUSf1nnd461fmhDH/GHA/afiweb/lhMbWX6TzwXYVT+5wuD+X6qDwmEYvvD9iST+iUCF32xXYS0mJbQXstXBXoL8=
