language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
- windows
matrix:
  exclude:
  - os: windows
    node_js: stable
after_success: npm run coverage
jobs:
  include:
  - stage: npm publish
    node_js: lts/*
    os: linux
    script: echo deploy to npm
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: BlW2E8dVhjvREiCWt1zqN42tCafsN1F0Jgruwh+uQxbKZujdgRfBGM8LStKnS6zdGTuPBHrL1DX8gjyxyOmo1Z6+NRc/1Ms/H/kVSXv4LUH9JBEiGDkHhawGoPTlHtw+JsHkZMQ7tqxKZYafta0SZTfmd7uVFLBWtK7epPyJz5hdVLYVOPC5RO2TLcs7GeBNN96gAkcc71wm0dYj2SlqVdw+uZOOWMRFXR5+CM29UT2BGIKfxpWDlIuyEH/1I/Ag5nROahkaPzNi24X69PUJgMgdIxYfDxHUkmjFKN4UUccX/+evXwcKZUcf3cOOkKkwByxqwqAz9ahzJf/upaEQ8vqhG6vAFRgP2duU1px6/NUXZjsNdse05RootcamOYOd/HKvL9cxXyaFd1alzInABVopwMdD28E0y3PDZqjq+x4l4b+GqNfDaVTH92P8sTSgMeffsULXVP5SHvoirdxMqdhSo1mBUUfnNkacYEqmCUGfQYGcJ+HaDgGWWqV0wmZGjq0y1EjTYjCkoWIlRZnlc1i+dy7dOSt4M9dwXGt5FikWuq+U9vIbChFoSmiPqjXAw4C8ad4NY4GeP9qrAQLkXhW1ZOgGiCBfJJ8obw/vFRYzrg1Ql5Y/+qbUklnqVplNCEXzd6pg/vRoMl/s1afeIV4aajwjnUkUoQs04ybf7ro=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: 2tHZjOhYXwRXniTuUOLzgbSAmQmQ9jjpjrF99h+NvvCYxFTckqobEaH7VnRDHuHn9/EC0NzU5q9wEa4UgiHnlPd4d5PE/jghj/9Ke1rA3Ss+JoGyJoIqEmuK+yIlQxbUOJ6PEO0MeVpsHALbyb+QZS1r8F2GnZlAB/KKfGHCZo1BbU+6R3GdR7frNlKp5VMtaKWtUc7EB7zBjDZpr4IxHnzDh+EulUQ6wxT+7/DinWlr8aH5vMq+LHG7eAwtO2OT9ufBdTvfUQ0eIky50VvQImJ7BpTyhcvKlgGk0Fo8tgXoQA4+w6bkgdyXBmtBYOHxanu2tPTyOsZWzZFfEnSe4fcRF93I6FmCGM1qacPM82BDMH92LVgjVmutelCGVaQgLuWo4dlQVJi9+oFB9sVW61WcdYQ4PMvbflPzExZvm8YL0DhA+hkvoAfv35eFDEqhuIfA45YnT/+/Gjfx8RNnBJrqXmcw+UQ8fArhLdrUFkWd3hiF4H+2wEmbDGc59q2zctpM4lVK4jm3PDcgcDiIqaWUnS75WlHQ0YSBM8RPdtUq9lKa2Ik6KWbPgIsY7a4k21/AEsGhxo6dN+yArmuOqx/7mglrHuQyVK7DZwF1EiaZNr7zM90ir/iITiALtySw6Mrwm/ew+dXyh5kMpmY+pzc8FARCbhGqRv0UQazGNzs=
